create schema if not exists rod;

CREATE TABLE sensors
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sensor_name VARCHAR(255)   NOT NULL,
    reading     NUMERIC(19, 6) NOT NULL,
    unit        VARCHAR(32)    NOT NULL,
    created_at  TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP
);