create schema if not exists rod;

CREATE TABLE IF NOT EXISTS sensor_reading
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sensor_id   UUID   NOT NULL,
    reading     NUMERIC(19, 6) NOT NULL,
    unit        VARCHAR(32)    NOT NULL,
    created_at  TIMESTAMP      NOT NULL
);

CREATE TABLE IF NOT EXISTS sensor (
    id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    sensor_name VARCHAR(255) UNIQUE NOT NULL,
    sensor_comment TEXT,
    public_key TEXT NOT NULL
);

CREATE TABLE actuator
(
    id            uuid DEFAULT RANDOM_UUID() PRIMARY KEY,
    actuator_name VARCHAR(100) NOT NULL,
    base_url      VARCHAR(255) NOT NULL
);

CREATE TABLE actuator_schedules
(
    id               uuid DEFAULT RANDOM_UUID() PRIMARY KEY,
    actuator_id      uuid NOT NULL,
    activation_time  TIME NOT NULL,
    duration_seconds INT NOT NULL,
    enabled          BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_actuator_schedule_actuator
        FOREIGN KEY (actuator_id) REFERENCES actuator(id) ON DELETE CASCADE
);