create schema if not exists rod;


CREATE TABLE IF NOT EXISTS sensor_reading
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sensor_name VARCHAR(255)   NOT NULL,
    reading     NUMERIC(19, 6) NOT NULL,
    unit        VARCHAR(32)    NOT NULL,
    created_at  TIMESTAMP      NOT NULL
);

CREATE TABLE IF NOT EXISTS sensor (
    id UUID PRIMARY KEY,
    public_key TEXT NOT NULL
);