ALTER TABLE actuator_schedules
    ADD COLUMN days_of_week VARCHAR(100) NOT NULL DEFAULT 'MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,SUNDAY';

ALTER TABLE actuator_schedules
    ADD COLUMN months VARCHAR(120) NOT NULL DEFAULT 'JANUARY,FEBRUARY,MARCH,APRIL,MAY,JUNE,JULY,AUGUST,SEPTEMBER,OCTOBER,NOVEMBER,DECEMBER';